// <auto-generated />
using FAQs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQs.Migrations
{
    [DbContext(typeof(FaqsContext))]
    [Migration("20230922091332_InitialFaqMigration")]
    partial class InitialFaqMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQs.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "gen",
                            CategoryName = "General"
                        },
                        new
                        {
                            CategoryID = "hist",
                            CategoryName = "History"
                        });
                });

            modelBuilder.Entity("FAQs.Models.Faqs", b =>
                {
                    b.Property<int>("FaqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqID"));

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FaqAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaqQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaqID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TopicID");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqID = 1,
                            CategoryID = "gen",
                            FaqAnswer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            FaqQuestion = "What is C#?",
                            TopicID = "cs"
                        },
                        new
                        {
                            FaqID = 2,
                            CategoryID = "hist",
                            FaqAnswer = "In 2002.",
                            FaqQuestion = "When was C# first released?",
                            TopicID = "cs"
                        },
                        new
                        {
                            FaqID = 3,
                            CategoryID = "gen",
                            FaqAnswer = "A general purpose scripting language that executes in a web browser.",
                            FaqQuestion = "What is JavaScript?",
                            TopicID = "js"
                        },
                        new
                        {
                            FaqID = 4,
                            CategoryID = "hist",
                            FaqAnswer = "In 1995.",
                            FaqQuestion = "When was JavaScript first released?",
                            TopicID = "js"
                        },
                        new
                        {
                            FaqID = 5,
                            CategoryID = "gen",
                            FaqAnswer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            FaqQuestion = "What is Bootstrap?",
                            TopicID = "boot"
                        },
                        new
                        {
                            FaqID = 6,
                            CategoryID = "hist",
                            FaqAnswer = "In 2011.",
                            FaqQuestion = "When was Bootstrap first released?",
                            TopicID = "boot"
                        });
                });

            modelBuilder.Entity("FAQs.Models.Topic", b =>
                {
                    b.Property<string>("TopicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicID = "cs",
                            TopicName = "C#"
                        },
                        new
                        {
                            TopicID = "js",
                            TopicName = "JavaScript"
                        },
                        new
                        {
                            TopicID = "boot",
                            TopicName = "Bootstrap"
                        });
                });

            modelBuilder.Entity("FAQs.Models.Faqs", b =>
                {
                    b.HasOne("FAQs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQs.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
