// <auto-generated />
using DataAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(NoheasApparelContext))]
    [Migration("20231222005743_UpdatedProductName")]
    partial class UpdatedProductName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLibrary.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            BrandName = "Nike"
                        },
                        new
                        {
                            BrandID = 2,
                            BrandName = "Adidas"
                        },
                        new
                        {
                            BrandID = 3,
                            BrandName = "Puma"
                        },
                        new
                        {
                            BrandID = 4,
                            BrandName = "Crocs"
                        });
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Shoes"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Hoodies/Pullovers"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Slides"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Caps"
                        });
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"));

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            GenderName = "Men"
                        },
                        new
                        {
                            GenderID = 2,
                            GenderName = "Women"
                        },
                        new
                        {
                            GenderID = 3,
                            GenderName = "Unisex"
                        });
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("productID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("GenderID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productID = 1,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 2,
                            ProductColor = "Olive Strata",
                            ProductDescription = "When it's not cold enough for a beanie but you need a little extra protection, this adidas golf hat has you covered. It's made of sturdy twill with an insulated lining to keep you warm during chilly rounds. A moisture-absorbing sweatband keeps you dry and comfortable from first drive to final putt.",
                            ProductImageURL = "~/content/images/adidas_cap_Insulated_Quilted_5-Panel_Hat_Green_HY5996_01_standard_W.jpeg",
                            ProductName = "Insulated Quilted 5 Panel Hat (Womens)",
                            ProductPrice = 39.50m
                        },
                        new
                        {
                            productID = 2,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 3,
                            ProductColor = "Black",
                            ProductDescription = "Look effortlessly cool in this adidas bucket hat. Whether you're making a fashion statement or just trying to keep the sun out of your eyes, this polyester hat is ideal for those who value utility as much as style. The best part is, when you're done wearing it you can fold it into its own carrying pouch, complete with a strap.\r\n\r\nMade with a series of recycled materials, and at least 40% recycled content, this product represents just one of our solutions to help end plastic waste.",
                            ProductImageURL = "~/content/images/adidas_cap_Packable_Bucket_Hat_Black_GB4276_06_standard_W.jpeg",
                            ProductName = "Packable Bucket Hat (Unisex)",
                            ProductPrice = 32.50m
                        },
                        new
                        {
                            productID = 3,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "This men's hat has low-key Trefoil style with an embroidered logo on the front. Made of washed canvas, the hat has a crushable, packable design and an adjustable back strap so you can personalize the fit.",
                            ProductImageURL = "~/content/images/adidas_cap_Relaxed_Strap-Back_Hat_Black_BH7139_04_standard_W.jpeg",
                            ProductName = "Relaxed Strap-Back Hat (Mens)",
                            ProductPrice = 32.50m
                        },
                        new
                        {
                            productID = 4,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "White",
                            ProductDescription = "This men's hat has low-key Trefoil style with an embroidered logo on the front. Made of washed canvas, the hat has a crushable, packable design and an adjustable back strap so you can personalize the fit.",
                            ProductImageURL = "~/content/images/adidas_cap_Relaxed_Strap-Back_Hat_White_BH7142_04_standard_W.jpeg",
                            ProductName = "White Relaxed Strap-Back Hat (Mens)",
                            ProductPrice = 32.50m
                        },
                        new
                        {
                            productID = 5,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 2,
                            ProductColor = "Linen Green",
                            ProductDescription = "This adidas cap works just as well with casual outfits as with workout gear. Subtly embroidered with flowing script, it adds just a touch of sporty detail to your look. It's made with cotton for a soft feel, while the sweatband mops up any moisture to keep you cool and comfortable.",
                            ProductImageURL = "~/content/images/adidas_cap_Saturday_2.0_Plus_Hat_Silver_GB4331_06_standard_W.jpeg",
                            ProductName = "Saturday 2.0 Plus Hat (Womens)",
                            ProductPrice = 33.00m
                        },
                        new
                        {
                            productID = 6,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Rain or shine, the trail still calls. Get in your run or make the hike happen in wet weather with this Terrex hat. adidas RAIN.RDY seals out water to keep you running, hiking or exploring — all while keeping your head dry. The seam-sealed design keeps it waterproof, while a moisture-wicking headband keeps sweat out of your face.",
                            ProductImageURL = "~/content/images/adidas_cap_TERREX_RAIN.RDY_Cap_Black_HY3790_01_standard_W.jpeg",
                            ProductName = "TERREX RAIN.RDY Cap (Mens)",
                            ProductPrice = 35.00m
                        },
                        new
                        {
                            productID = 7,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "Blue",
                            ProductDescription = "Rain or shine, the trail still calls. Get in your run or make the hike happen in wet weather with this Terrex hat. adidas RAIN.RDY seals out water to keep you running, hiking or exploring — all while keeping your head dry. The seam-sealed design keeps it waterproof, while a moisture-wicking headband keeps sweat out of your face.",
                            ProductImageURL = "~/content/images/adidas_cap_TERREX_RAIN_RDY_Cap_Blue_HY3791_01_standard_W.jpeg",
                            ProductName = "TERREX_RAIN_RDY Cap (Mens)",
                            ProductPrice = 35.00m
                        },
                        new
                        {
                            productID = 8,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Fresh adidas Originals style for the streets. This six-panel cap combines a flat brim with a raised Trefoil logo embroidery. A snap-back closure lets you fine-tune the fit.",
                            ProductImageURL = "~/content/images/adidas_cap_Trefoil_Chain_Snap-Back_Cap_Black_standard.jpeg",
                            ProductName = "Trefoil Chain Snap-Back Cap (Mens)",
                            ProductPrice = 36.00m
                        },
                        new
                        {
                            productID = 9,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Sunny days are more fun under the brim of this adidas boonie hat. Not only does it shade your eyes, it also steps up your style. A zip pocket and adjustable chin strap seal the deal on utilitarian style. All that's left to do is to grab your towel and head to the beach.",
                            ProductImageURL = "~/content/images/adidas_cap_Utility_Boonie_Hat_Black_GA5295_01_standard_W.jpeg",
                            ProductName = "Utility Boonie Hat (Mens)",
                            ProductPrice = 50.00m
                        },
                        new
                        {
                            productID = 10,
                            BrandID = 2,
                            CategoryID = 4,
                            GenderID = 3,
                            ProductColor = "Shadow Red",
                            ProductDescription = "There's nothing more timeless than a classic baseball hat. Throw on this adidas cap and bring some effortless style to any outfit. Its soft fleece build and 3D embroidered Badge of Sport give it that premium touch that elevates your look.",
                            ProductImageURL = "~/content/images/adidas_cap_Wool_Baseball_Hat_Burgundy_IJ7300_01_standard_W.jpeg",
                            ProductName = "Wool Baseball Hat (Unisex)",
                            ProductPrice = 20.00m
                        },
                        new
                        {
                            productID = 11,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Got a cold-weather round in store? Game on. Pull on this adidas golf hoodie and you won't give the temperature a second thought. It's made with COLD.RDY that traps heat against the body to keep you warm in chilly conditions. Soft fleece feels extra cosiness against your skin, and a bungee-adjustable hem lets you seal out cool air. When light rain hits, you'll stay dry thanks to the water-repellent finish.",
                            ProductImageURL = "~/content/images/adidas_COLD_RDY_Hoodie_Black_IL9632_21_mens.jpeg",
                            ProductName = "COLD RDY Hoodie (Mens)",
                            ProductPrice = 71.00m
                        },
                        new
                        {
                            productID = 12,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Black/White",
                            ProductDescription = "When they go loud, you go low-key. This adidas hoodie has plenty of understated appeal. Made from cotton-blend fleece, it keeps you warm from your head to your hands, thanks to the adjustable hood and the cozy front pocket. 3-Stripes at the shoulders add a classic touch.",
                            ProductImageURL = "~/content/images/adidas_Essentials_Fleece_3-Stripes_Full-Zip_Hoodie_Black_IB4029_21_mens.jpeg",
                            ProductName = "Essentials Fleece 3-Stripes Full-Zip Hoodie (Mens)",
                            ProductPrice = 45.00m
                        },
                        new
                        {
                            productID = 13,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Grey",
                            ProductDescription = "When they go loud, you go low-key. This adidas hoodie has plenty of understated appeal. Made from cotton-blend fleece, it keeps you warm from your head to your hands, thanks to the adjustable hood and the cozy front pocket. 3-Stripes at the shoulders add a classic touch.",
                            ProductImageURL = "~/content/images/adidas_Essentials_Fleece_3-Stripes_Full-Zip_Hoodie_Grey_IJ6479_21_mens.jpeg",
                            ProductName = "Essentials Fleece 3-Stripes Full-Zip Hoodie (Mens)",
                            ProductPrice = 45.00m
                        },
                        new
                        {
                            productID = 14,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "An everyday essential with an eye-catching graphic. The comfortable loose fit, French terry construction and classic silhouette make this adidas hoodie an instant go-to. Trefoil logos on the front and back get an elemental update with photorealistic water droplets that'll have passersby doing a double take.",
                            ProductImageURL = "~/content/images/adidas_Graphic_Liquid_Trefoil_Hoodie_Black_II8170_21_mens.jpeg",
                            ProductName = "Graphic Liquid Trefoil Hoodie (Mens)",
                            ProductPrice = 62.00m
                        },
                        new
                        {
                            productID = 15,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 3,
                            ProductColor = "Black",
                            ProductDescription = "Whether it's chilly out or you just feel like hanging at home, this adidas hoodie lets you make the most out of a cold day. It's made of soft, heavyweight French terry fabric to keep you warm, and it's styled to be worn by all genders. The loose fit gives you a relaxed feel, so you can lounge around comfortably all day long.",
                            ProductImageURL = "~/content/images/adidas_Lounge_Heavy_French_Terry_Hoodie_Black_IC4084_25_mens.jpeg",
                            ProductName = "Lounge Heavy French Terry Hoodie (Unisex)",
                            ProductPrice = 99.00m
                        },
                        new
                        {
                            productID = 16,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Arctic Night",
                            ProductDescription = "Stand out from tee to green in this adidas golf sweatshirt. Soft polar fleece gives a luxe feel while keeping you cozy on the course during chilly weather. Ribbed cuffs and hem seal out the cold, and a durable water-repellent finish keeps you dry through misty rounds and occasional light showers.",
                            ProductImageURL = "~/content/images/adidas_Oasis_Crew_Sweatshirt_Turquoise_IB1982_21_mens.jpeg",
                            ProductName = "Oasis Crew Sweatshirt Turquoise (Mens)",
                            ProductPrice = 99.00m
                        },
                        new
                        {
                            productID = 17,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Bright Red",
                            ProductDescription = "Chilly weather calls for a lightweight layer. This adidas golf pullover is made of soft knit for comfort on the course. Moisture-absorbing AEROREADY keeps you dry, and built-in UV coverage lets you play with confidence on sunny days.",
                            ProductImageURL = "~/content/images/adidas_Quarter-Zip_Pullover_Red_IJ0185_25_mens.jpeg",
                            ProductName = "Quarter-Zip Pullover (Mens)",
                            ProductPrice = 47.00m
                        },
                        new
                        {
                            productID = 18,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Blue / White",
                            ProductDescription = "Sometimes less is more. The adidas Trefoil Essentials crewneck perfects effortless style and timeless design. An embroidered Trefoil adorns the clean silhouette. Made for everyday casual wear, this crewneck serves laid-back vibes with a simple yet bold look.",
                            ProductImageURL = "~/content/images/adidas_Trefoil_Essentials_Crewneck_Blue_IR7781_21_mens.jpeg",
                            ProductName = "Trefoil Essentials Crewneck (Mens)",
                            ProductPrice = 41.00m
                        },
                        new
                        {
                            productID = 19,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Whether you're on the mat in the studio or at home, this super-soft adidas sweatshirt lets you breathe easily. Perfect your poses in its free-flowing design, detailed with a hood, a zip pocket and shaped cuffs. In the mood for hot yoga? AEROREADY manages moisture so you can keep your focus. The back relays a message to remember: Allow yourself to grow.",
                            ProductImageURL = "~/content/images/adidas_Yoga_Training_Hooded_Sweatshirt_Black_IN7922_21_mens.jpeg",
                            ProductName = "Yoga Training Hooded Sweatshirt (Mens)",
                            ProductPrice = 51.00m
                        },
                        new
                        {
                            productID = 20,
                            BrandID = 2,
                            CategoryID = 2,
                            GenderID = 1,
                            ProductColor = "Dark Grey Heather",
                            ProductDescription = "When they go loud, you go low-key. This adidas hoodie has plenty of understated appeal. Made from cotton-blend fleece, it keeps you warm from your head to your hands, thanks to the adjustable hood and the cozy front pocket. 3-Stripes at the shoulders add a classic touch.",
                            ProductImageURL = "~/content/images/adidas_Essentials_Fleece_3-Stripes_Full-Zip_Hoodie_Grey_IJ6480_21_mens.jpeg",
                            ProductName = "Essentials Fleece 3-Stripes Full-Zip Hoodie (Mens)",
                            ProductPrice = 48.00m
                        },
                        new
                        {
                            productID = 21,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "Night Stadium/Black/Flat Pewter/Total Orange",
                            ProductDescription = "Clean and supreme, the AJ3 returns with all of its classic style and grace. Quality leather in the upper—with that luxurious elephant print texture—combines with visible Nike Air in the sole to make a comfortable, everyday icon.",
                            ProductImageURL = "~/content/images/Air_Jordan_3_Fear.jpg",
                            ProductName = "Air Jordan 3 Fear (Mens)",
                            ProductPrice = 211.00m
                        },
                        new
                        {
                            productID = 22,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White/Black/White/Royal Blue",
                            ProductDescription = "Inspired by the original that debuted in 1985, the Air Jordan 1 Low offers a clean, classic look that's familiar yet always fresh. With an iconic design that pairs perfectly with any 'fit, these kicks ensure you'll always be on point.",
                            ProductImageURL = "~/content/images/AirJordan_1_Low.jpg",
                            ProductName = "Air Jordan 1 Low (Mens)",
                            ProductPrice = 116.00m
                        },
                        new
                        {
                            productID = 23,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White/Midnight Navy/Black",
                            ProductDescription = "Feel unbeatable, from the tee box to the final putt. Inspired by one of the most iconic sneakers of all time, the Air Jordan 1 G is an instant classic on the course. With Air cushioning underfoot, a Wings logo on the heel and an integrated traction pattern to help you power through your swing, it delivers all the clubhouse cool of the original AJ1—plus everything you need to play 18 holes in comfort.",
                            ProductImageURL = "~/content/images/AirJordan_1_Low_G.jpg",
                            ProductName = "Air Jordan 1 Low G (Mens)",
                            ProductPrice = 155.00m
                        },
                        new
                        {
                            productID = 24,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White/Black/Gym Red",
                            ProductDescription = "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colors and crisp leather give it a distinct identity.",
                            ProductImageURL = "~/content/images/AirJordan_1_Mid_Red.jpg",
                            ProductName = "Air Jordan 1 Mid Red (Mens)",
                            ProductPrice = 130.00m
                        },
                        new
                        {
                            productID = 25,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White",
                            ProductDescription = "Inspired by the original AJ1, the Air Jordan 1 Mid offers fans a chance to follow in MJ's footsteps. Fresh color trims the clean, classic materials, imbuing modernity into a classic design.",
                            ProductImageURL = "~/content/images/AirJordan_1_Mid_White.jpg",
                            ProductName = "Air Jordan 1 Mid White (Mens)",
                            ProductPrice = 131.00m
                        },
                        new
                        {
                            productID = 26,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "Light Orewood Brown/Sail/Celestial Gold/Bright Citrus",
                            ProductDescription = "Premium suede and Jordan Brand's signature Formula 23 foam come together to give you an extra luxurious (and extra cozy) AJ1. You don't need to play \"either or\" when it comes to choosing style or comfort with this one—which is nice, 'cause you deserve both.",
                            ProductImageURL = "~/content/images/AirJordan_1_Zoom_CMFT_2.jpg",
                            ProductName = "Air Jordan 1 Zoom CMFT 2 (Mens)",
                            ProductPrice = 132.00m
                        },
                        new
                        {
                            productID = 27,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White/Black",
                            ProductDescription = "From us, to you—this release of the AJ11 is a \"Thank You\" to our day ones and those committed to carrying the Jordan legacy forward. Celebrating a heritage colorway, this classic honors MJ's legacy while elevating the materials for those pushing culture to new heights. The upper is designed with a mix of premium materials like luxe leather, along with a smooth knit collar. The glossy patent leather mudguard gleams just like the original. A tinted translucent outsole offers a clean finish while the welded gold Jumpman radiates the shoe's championship roots.",
                            ProductImageURL = "~/content/images/AirJordan_11_Gratitude.jpg",
                            ProductName = "Air Jordan 11 Gratitude (Mens)",
                            ProductPrice = 300.00m
                        },
                        new
                        {
                            productID = 28,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "White/Wheat",
                            ProductDescription = "Celebrate 25 years of the AJ13 with a colorway bring-back. Dimpled full-grain White leather gets a soft, synthetic Wheat suede treatment for a boost of elegance. Capping it off, the green cat's eye emblem on the heel and panther paw-inspired outsole honor MJ's slick \"Black Cat\" alter ego.",
                            ProductImageURL = "~/content/images/AirJordan_13_Wheat.jpg",
                            ProductName = "Air Jordan 13 Wheat (Mens)",
                            ProductPrice = 200.00m
                        },
                        new
                        {
                            productID = 29,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "Medium Olive/Cargo Khaki/Black/Pale Vanilla",
                            ProductDescription = "Here's the '89 classic, done up in elegant earth tones. Suede, leather and textiles come together in the upper for a truly textured look. And of course, all your favorite AJ4 elements are there too—like the floating eyestays and mesh-inspired side panels.",
                            ProductImageURL = "~/content/images/AirJordan_4_Craft_Olive.jpg",
                            ProductName = "Air Jordan 4 Craft Olive (Mens)",
                            ProductPrice = 210.00m
                        },
                        new
                        {
                            productID = 30,
                            BrandID = 1,
                            CategoryID = 1,
                            GenderID = 1,
                            ProductColor = "Black/Metallic Silver/Gunsmoke",
                            ProductDescription = "Your cold-weather kicks have arrived. This AJ8 is designed with luxe leather, reflective elements and premium suede for durable style you can put to the test. Black and Gunsmoke pair with Metallic Silver for sleek seasonal style. It's an icy look that feels cool, whether it's winter or not.",
                            ProductImageURL = "~/content/images/AirJordan_8_Winterized.jpg",
                            ProductName = "Air Jordan 8 Winterized (Mens)",
                            ProductPrice = 210.00m
                        },
                        new
                        {
                            productID = 31,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Velvet Brown",
                            ProductDescription = "Cozy, but make it cool. This roomy, easy-fitting crew features mid-weight fleece for a soft feel. Combine that with elevated finishing touches and you have an everyday staple that truly stands out.",
                            ProductImageURL = "~/content/images/nike_jordan-brooklyn-fleece-womens-crewneck-sweatshirt-zvZ5ms.jpg",
                            ProductName = "Nike Jordan Brooklyn fleece crewneck sweatshirt (Womens)",
                            ProductPrice = 210.00m
                        },
                        new
                        {
                            productID = 32,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Red Stardust",
                            ProductDescription = "Meet your new favorite sweatshirt. The one you pull out of the dirty clothes pile because it’s too good not to wear one more time. (No one’s gonna know.) Super soft with a slightly oversized fit and extra volume in the sleeves, it's easy to pull on and perfect for layering.",
                            ProductImageURL = "~/content/images/nike_jordan-flight-fleece-womens-crewneck-sweatshirt-rtRM9K.jpg",
                            ProductName = "Jordan flight fleece crewneck sweatshirt (Womens)",
                            ProductPrice = 88.00m
                        },
                        new
                        {
                            productID = 33,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Black Heather",
                            ProductDescription = "Get cozy in a classic hoodie. Featuring a slightly fuzzy, heavyweight fleece in a roomy fit, you'll brave the cold in style. Satin lining on the hood means you can add coverage without worrying about your hair.",
                            ProductImageURL = "~/content/images/nike_jordan-flight-fleece-womens-winterized-hoodie-CGbKGT.jpg",
                            ProductName = "Jordan flight fleece winterized hoodie (Womens)",
                            ProductPrice = 108.00m
                        },
                        new
                        {
                            productID = 34,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Rugged Orange/Black",
                            ProductDescription = "Rise up and transform your wardrobe with strong cozy vibes. You're sure to fall in love with the soft feel of brushed fleece, while the roomy design of this cardigan makes you feel—and look—stylishly carefree.",
                            ProductImageURL = "~/content/images/nike_Sportswear_Phoenix_fleece.jpg",
                            ProductName = "Nike Sportswear Phoenix fleece (Womens)",
                            ProductPrice = 110.00m
                        },
                        new
                        {
                            productID = 35,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Diffused Blue/White",
                            ProductDescription = "Club Fleece sweatshirts, universally loved for their coziness and consistency, are for everyone. Always soft and made with a relaxed fit, they’re basics that help you do more. An essential for cold-weather layering, this crew-neck option is a quick and easy way to add warmth to your favorite puffer or jacket.",
                            ProductImageURL = "~/content/images/nike_sportswear-club-fleece-womens-crew-neck-sweatshirt-plus-size-DtqkgP.jpg",
                            ProductName = "Nike Sportswear Club Fleece Crewneck Sweatshirt (Womens)",
                            ProductPrice = 40.00m
                        },
                        new
                        {
                            productID = 36,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Fireberry/White",
                            ProductDescription = "Club Fleece sweatshirts, universally loved for their coziness and consistency, are for everyone. Always soft and made with a relaxed fit, they’re basics that help you do more. An essential for cold weather, this cozy pullover has just enough room to layer comfortably without feeling too big.",
                            ProductImageURL = "~/content/images/nike_sportswear-club-fleece-womens-logo-pullover-hoodie-07xm3D.jpg",
                            ProductName = "Nike Sportswear Club Fleece (Womens)",
                            ProductPrice = 80.00m
                        },
                        new
                        {
                            productID = 37,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Ale Brown/Cacao Wow",
                            ProductDescription = "This easy-fitting hoodie pairs soft fleece with tape-lined sleeves for a fresh-off-the-track finish. Smooth on the outside, slightly fuzzy on the inside, our midweight semi-brushed fleece helps keep you cozy while still being breezy. It’s a comfy layer to wear year-round, perfect for those tricky in-between temps.",
                            ProductImageURL = "~/content/images/nike_sportswear-essential-womens-fleece-hoodie-4803DS.jpg",
                            ProductName = "Nike Sportswear Essential (Womens)",
                            ProductPrice = 81.00m
                        },
                        new
                        {
                            productID = 38,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Midnight Navy/Black",
                            ProductDescription = "Grounded in style, comfort and versatility, meet our take on luxury loungewear. Our roomiest fit paired with exaggerated details (like the oversized pocket and taller ribbing) ensures this sweatshirt is anything but basic. All that's left to decide is whether to style it with the matching shorts or other pieces from your wardrobe.",
                            ProductImageURL = "~/content/images/nike_sportswear-phoenix-fleece-womens-over-oversized-crew-neck-sweatshirt-nTshQw.jpg",
                            ProductName = "Nike Sportswear Phoenix Fleece (Womens)",
                            ProductPrice = 81.00m
                        },
                        new
                        {
                            productID = 39,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Anthracite",
                            ProductDescription = "Rise up and transform your fleece wardrobe with strong cozy vibes. Our midweight brushed fleece feels extra soft on the inside and smooth on the outside, helping you stay comfortable while keeping its structured shape. With a washed aesthetic and exaggerated details, this crew-neck sweatshirt gives you a broken-in look that's anything but basic.",
                            ProductImageURL = "~/content/images/nike_sportswear-phoenix-fleece-womens-oversized-crew-neck-sweatshirt-wbNcml.jpg",
                            ProductName = "Nike Sportswear Phoenix Fleece (Womens)",
                            ProductPrice = 90.00m
                        },
                        new
                        {
                            productID = 40,
                            BrandID = 1,
                            CategoryID = 2,
                            GenderID = 2,
                            ProductColor = "Midnight Navy/Black",
                            ProductDescription = "Grounded in style, comfort and versatility, meet our take on luxury loungewear. This classic hoodie helps you stay cozy all day long, thanks to midweight fleece that feels soft yet structured. Plus, exaggerated details (like taller ribbing and oversized fit) give you a trend-right look.",
                            ProductImageURL = "~/content/images/nike_sportswear-phoenix-fleece-womens-oversized-pullover-hoodie-QnWVHw.jpg",
                            ProductName = "Nike Sportswear Phoenix Fleece (Womens)",
                            ProductPrice = 75.00m
                        },
                        new
                        {
                            productID = 41,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Espresso",
                            ProductDescription = "Travel. Exploration. Adventures near and far. The look and feel of our Classic All-Terrain Clog, now in sandal form. With a more rugged outsole, two upper straps and an adjustable turbo strap, the ground beneath your feet has never felt more surmountable. Seven holes on each sandal allow for personalization with Jibbitz™ charms and a lightweight Croslite™ construction makes them a practical and packable choice for any outing. It's time to shift into all-wheel drive. Flip that strap back and go find your fun!",
                            ProductImageURL = "~/content/images/p_crocs_mens_ALL_TERRAIN_SUMMIT_SANDAL.jpeg",
                            ProductName = "ALL TERRAIN SUMMIT SANDAL (Mens)",
                            ProductPrice = 29.00m
                        },
                        new
                        {
                            productID = 42,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Bone / Multi",
                            ProductDescription = "The comfortable Classic Crocs Sandal now sports our new marbled Croslite™ material that creates a fun, colorful effect. While all marbled sandals have the same wavy look, no two are exactly alike. Enjoy iconic Crocs comfort and stylish design in this unique casual sandal that’s perfect for everyday wear.",
                            ProductImageURL = "~/content/images/p_crocs_mens_CLASSIC_CROCS_MARBLED_SANDAL.jpeg",
                            ProductName = "CLASSIC CROCS MARBLED SANDAL (Mens)",
                            ProductPrice = 31.00m
                        },
                        new
                        {
                            productID = 43,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Bone",
                            ProductDescription = "Original. Customizable. Comfortable. The ever-comfortable Classic II Slide gets the customization upgrade fans have been asking for in the Classic Crocs Slide: holes for Jibbitz™ charms! Each slide has room for 13 charms so you can load up your sandals with tons of personality. Original Croslite™ foam cushion will keep you comfortably supported from the beach to backyard gatherings and beyond. Choose your color and slide into a new favorite!",
                            ProductImageURL = "~/content/images/P_crocs_mens_classic_slide.jpeg",
                            ProductName = "Crocs Classic Slides (Mens)",
                            ProductPrice = 31.00m
                        },
                        new
                        {
                            productID = 44,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Bone",
                            ProductDescription = "All Flip, No Flop! Sporty and lightweight with the signature athletic stripe, the Crocband™ Flip is a colorful and incredibly comfortable warm-weather choice that pairs perfectly with shorts, slacks or swimwear. Constructed of easy-to-clean Croslite™ material, it’s ready for the beach, garden or anywhere else you choose to get your summer on!",
                            ProductImageURL = "~/content/images/p_crocs_mens_crocband_flip.jpeg",
                            ProductName = "Crocband Flip (Mens)",
                            ProductPrice = 31.00m
                        },
                        new
                        {
                            productID = 45,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Flame / White",
                            ProductDescription = "Enjoy the ever-comfortable Classic Crocs Slide now available in with a marbled effect. While all shoes have the same wavy look, no two are exactly alike, so you’ll have a completely unique pair. This special slide also features the Croslite™ footbed you love for an enjoyable ride. Choose your color and slide into a new favorite!",
                            ProductImageURL = "~/content/images/p_mens_crocs_CLASSIC_CROCS_MARBLED_SLIDE.jpeg",
                            ProductName = "CLASSIC CROCS MARBLED SLIDE (Mens)",
                            ProductPrice = 31.00m
                        },
                        new
                        {
                            productID = 46,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Puma Black-High Rise",
                            ProductDescription = "Streetwear, meet beachwear. The RS-Sandal takes the signature RS style for a ride with future-forward.",
                            ProductImageURL = "~/content/images/puma_mens_black_RS-Sandal.jpeg",
                            ProductName = "Puma RS-Sandal (Mens)",
                            ProductPrice = 54.00m
                        },
                        new
                        {
                            productID = 47,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Black",
                            ProductDescription = "Slip into extreme comfort and set the trend with the new Shibui Cat Sandals from PUMA. These cozy kicks come with a fully injected IMEVA slide for a perfectly snug feel at home or wherever your feet may carry you. Minimalist PUMA Cat Logo branding adds a smooth finish.",
                            ProductImageURL = "~/content/images/puma_mens_Shibui-Cat-Slides.jpeg",
                            ProductName = "Shibui Cat Slides (Mens)",
                            ProductPrice = 24.99m
                        },
                        new
                        {
                            productID = 48,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Marshmallow-Puma Black",
                            ProductDescription = "Streetwear, meet beachwear. The RS-Sandal takes the signature RS style for a ride with future-forward detailing and ultra-cushioned RS tech.",
                            ProductImageURL = "~/content/images/puma_mens_RS-Sandal.jpeg",
                            ProductName = "RS-Sandal (Mens)",
                            ProductPrice = 54.99m
                        },
                        new
                        {
                            productID = 49,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "Puma Black-Puma White",
                            ProductDescription = "Prioritize comfort without sacrificing style in these on-trend Softride slides. Whether you’re cooling down after a workout or rocking a casual summertime look, this footwear is designed to provide the best underfoot cushioning. The Softride footbed ensures every step you take feels sumptuous, while the durable synthetic strap is adjustable, guaranteeing the snuggest fit.",
                            ProductImageURL = "~/content/images/puma_mens_Softride-Slides.jpeg",
                            ProductName = "Softride Slides (Mens)",
                            ProductPrice = 39.99m
                        },
                        new
                        {
                            productID = 50,
                            BrandID = 4,
                            CategoryID = 3,
                            GenderID = 1,
                            ProductColor = "White",
                            ProductDescription = "Prioritize comfort without sacrificing style in these on-trend Softride slides. Whether you’re cooling down after a workout or rocking a casual summertime look, this footwear is designed to provide the best underfoot cushioning. The Softride footbed ensures every step you take feels sumptuous, while the durable synthetic strap is adjustable, guaranteeing the snuggest fit.",
                            ProductImageURL = "~/content/images/puma_mens_white_Softride-Slides.jpeg",
                            ProductName = "Softride Slides",
                            ProductPrice = 39.99m
                        });
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Product", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLibrary.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
