// <auto-generated />
using BikeShop_HOT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeShop_HOT.Migrations
{
    [DbContext(typeof(BikeShopContext))]
    [Migration("20231015115242_secondMig")]
    partial class secondMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeShop_HOT.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Accessories"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Bikes"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Components"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Car racks"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Wheels"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Uncategorized Products"
                        });
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "15127 NE 24th, #383",
                            City = "Redmond",
                            FirstName = "Suzanne",
                            LastName = "Viescas",
                            PhoneNumber = "425-555-2686",
                            State = "WA",
                            ZipCode = "98052"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "122 Spring River Drive",
                            City = "Duvall",
                            FirstName = "William",
                            LastName = "Thompson",
                            PhoneNumber = "425-555-2681",
                            State = "WA",
                            ZipCode = "98019"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "Route 2, Box 203B",
                            City = "Auburn",
                            FirstName = "Gary",
                            LastName = "Hallmark",
                            PhoneNumber = "253-555-2676",
                            State = "WA",
                            ZipCode = "98013"
                        },
                        new
                        {
                            CustomerID = 4,
                            Address = "672 Lamont Ave",
                            City = "Houston",
                            FirstName = "Robert",
                            LastName = "Brown",
                            PhoneNumber = "713-555-2491",
                            State = "TX",
                            ZipCode = "77201"
                        },
                        new
                        {
                            CustomerID = 5,
                            Address = "4110 Old Redmond Rd.",
                            City = "Redmond",
                            FirstName = "Dean",
                            LastName = "McCrae",
                            PhoneNumber = "425-555-2506",
                            State = "WA",
                            ZipCode = "98052"
                        },
                        new
                        {
                            CustomerID = 6,
                            Address = "15127 NE 24th, #383",
                            City = "Redmond",
                            FirstName = "John",
                            LastName = "Viescas",
                            PhoneNumber = "425-555-2511",
                            State = "WA",
                            ZipCode = "98052"
                        },
                        new
                        {
                            CustomerID = 7,
                            Address = "901 Pine Avenue",
                            City = "Portland",
                            FirstName = "Mariya",
                            LastName = "Sergienko",
                            PhoneNumber = "503-555-2526",
                            State = "OR",
                            ZipCode = "97208"
                        },
                        new
                        {
                            CustomerID = 8,
                            Address = "233 West Valley Hwy",
                            City = "San Diego",
                            FirstName = "Neil",
                            LastName = "Patterson",
                            PhoneNumber = "619-555-2541",
                            State = "CA",
                            ZipCode = "92199"
                        },
                        new
                        {
                            CustomerID = 9,
                            Address = "507 - 20th Ave. E. Apt. 2A",
                            City = "Seattle",
                            FirstName = "Andrew",
                            LastName = "Cencini",
                            PhoneNumber = "206-555-2601",
                            State = "WA",
                            ZipCode = "98105"
                        },
                        new
                        {
                            CustomerID = 10,
                            Address = "667 Red River Road",
                            City = "Austin",
                            FirstName = "Angel",
                            LastName = "Kennedy",
                            PhoneNumber = "512-555-2571",
                            State = "TX",
                            ZipCode = "78710"
                        },
                        new
                        {
                            CustomerID = 11,
                            Address = "Route 2, Box 203B",
                            City = "Woodinville",
                            FirstName = "Alaina",
                            LastName = "Hallmark",
                            PhoneNumber = "425-555-2631",
                            State = "WA",
                            ZipCode = "98072"
                        },
                        new
                        {
                            CustomerID = 12,
                            Address = "13920 S.E. 40th Street",
                            City = "Bellevue",
                            FirstName = "Liz",
                            LastName = "Keyser",
                            PhoneNumber = "425-555-2556",
                            State = "WA",
                            ZipCode = "98006"
                        },
                        new
                        {
                            CustomerID = 13,
                            Address = "2114 Longview Lane",
                            City = "San Diego",
                            FirstName = "Rachel",
                            LastName = "Patterson",
                            PhoneNumber = "619-555-2546",
                            State = "CA",
                            ZipCode = "92199"
                        },
                        new
                        {
                            CustomerID = 14,
                            Address = "611 Alpine Drive",
                            City = "Palm Springs",
                            FirstName = "Sam",
                            LastName = "Abolrous",
                            PhoneNumber = "760-555-2611",
                            State = "CA",
                            ZipCode = "92263"
                        },
                        new
                        {
                            CustomerID = 15,
                            Address = "2601 Seaview Lane",
                            City = "Chico",
                            FirstName = "Darren",
                            LastName = "Gehring",
                            PhoneNumber = "530-555-2616",
                            State = "CA",
                            ZipCode = "95926"
                        },
                        new
                        {
                            CustomerID = 16,
                            Address = "101 NE 88th",
                            City = "Salem",
                            FirstName = "Jim",
                            LastName = "Wilson",
                            PhoneNumber = "503-555-2636",
                            State = "OR",
                            ZipCode = "97301"
                        },
                        new
                        {
                            CustomerID = 17,
                            Address = "66 Spring Valley Drive",
                            City = "Medford",
                            FirstName = "Manuela",
                            LastName = "Seidel",
                            PhoneNumber = "541-555-2641",
                            State = "OR",
                            ZipCode = "97501"
                        },
                        new
                        {
                            CustomerID = 18,
                            Address = "311 20th Ave. N.E.",
                            City = "Fremont",
                            FirstName = "David",
                            LastName = "Smith",
                            PhoneNumber = "510-555-2646",
                            State = "CA",
                            ZipCode = "94538"
                        },
                        new
                        {
                            CustomerID = 19,
                            Address = "12330 Kingman Drive",
                            City = "Glendale",
                            FirstName = "Zachary",
                            LastName = "Ehrlich",
                            PhoneNumber = "819-555-2721",
                            State = "CA",
                            ZipCode = "91209"
                        },
                        new
                        {
                            CustomerID = 20,
                            Address = "2424 Thames Drive",
                            City = "Bellevue",
                            FirstName = "Joyce",
                            LastName = "Bonnicksen",
                            PhoneNumber = "425-555-2726",
                            State = "WA",
                            ZipCode = "98006"
                        },
                        new
                        {
                            CustomerID = 21,
                            Address = "2500 Rosales Lane",
                            City = "Dallas",
                            FirstName = "Estella",
                            LastName = "Pundt",
                            PhoneNumber = "972-555-9938",
                            State = "TX",
                            ZipCode = "75260"
                        },
                        new
                        {
                            CustomerID = 22,
                            Address = "4501 Wetland Road",
                            City = "Long Beach",
                            FirstName = "Caleb",
                            LastName = "Viescas",
                            PhoneNumber = "562-555-0037",
                            State = "CA",
                            ZipCode = "90809"
                        },
                        new
                        {
                            CustomerID = 23,
                            Address = "2343 Harmony Lane",
                            City = "Seattle",
                            FirstName = "Julia",
                            LastName = "Schnebly",
                            PhoneNumber = "206-555-9936",
                            State = "WA",
                            ZipCode = "99837"
                        },
                        new
                        {
                            CustomerID = 24,
                            Address = "323 Advocate Lane",
                            City = "El Paso",
                            FirstName = "Mark",
                            LastName = "Rosales",
                            PhoneNumber = "915-555-2286",
                            State = "TX",
                            ZipCode = "79915"
                        },
                        new
                        {
                            CustomerID = 25,
                            Address = "3445 Cheyenne Road",
                            City = "El Paso",
                            FirstName = "Maria",
                            LastName = "Patterson",
                            PhoneNumber = "915-555-2291",
                            State = "TX",
                            ZipCode = "79915"
                        },
                        new
                        {
                            CustomerID = 26,
                            Address = "455 West Palm Ave",
                            City = "San Antonio",
                            FirstName = "Kirk",
                            LastName = "DeGrasse",
                            PhoneNumber = "210-555-2311",
                            State = "TX",
                            ZipCode = "78284"
                        },
                        new
                        {
                            CustomerID = 27,
                            Address = "877 145th Ave SE",
                            City = "Portland",
                            FirstName = "Luke",
                            LastName = "Patterson",
                            PhoneNumber = "503-555-2316",
                            State = "OR",
                            ZipCode = "97208"
                        });
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Address = "16 Maple Lane",
                            City = "Auburn",
                            FirstName = "Ann",
                            LastName = "Patterson",
                            PhoneNumber = "253-555-2591",
                            State = "WA",
                            ZipCode = "98002"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Address = "122 Spring River Drive",
                            City = "Duvall",
                            FirstName = "Mary",
                            LastName = "Thompson",
                            PhoneNumber = "425-555-2516",
                            State = "WA",
                            ZipCode = "98019"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Address = "908 W. Capital Way",
                            City = "Tacoma",
                            FirstName = "Matt",
                            LastName = "Berg",
                            PhoneNumber = "253-555-2581",
                            State = "WA",
                            ZipCode = "98413"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Address = "722 Moss Bay Blvd.",
                            City = "Kirkland",
                            FirstName = "Carol",
                            LastName = "Viescas",
                            PhoneNumber = "425-555-2576",
                            State = "WA",
                            ZipCode = "98033"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Address = "16679 NE 42nd Court",
                            City = "Redmond",
                            FirstName = "David",
                            LastName = "Viescas",
                            PhoneNumber = "425-555-2661",
                            State = "WA",
                            ZipCode = "98052"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Address = "455 West Palm Ave",
                            City = "San Antonio",
                            FirstName = "Kirk",
                            LastName = "DeGrasse",
                            PhoneNumber = "210-555-2311",
                            State = "TX",
                            ZipCode = "78284"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Address = "554 E. Wilshire Apt. 2A",
                            City = "Seattle",
                            FirstName = "Kathryn",
                            LastName = "Patterson",
                            PhoneNumber = "206-555-2697",
                            State = "WA",
                            ZipCode = "98105"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Address = "511 Lenora Ave",
                            City = "Bellevue",
                            FirstName = "Susan",
                            LastName = "McLain",
                            PhoneNumber = "425-555-2301",
                            State = "WA",
                            ZipCode = "98006"
                        });
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 4,
                            Description = "Greens Lick is a machine built trail designed by Trail Dynamics as a demonstration trail showing the forest service how eroded road beds could be converted to sustainable trail.",
                            Image = "~/content/images/AeroFlo_ATB_Wheels.jpg",
                            Name = "AeroFlo ATB Wheels",
                            Price = 189m,
                            Qty = 40
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "This trail can be sandy during dry summer months and is best after rain, in the spring or fall. Rocks for texture, obstacles for fun and some short fast downhils in this 2.",
                            Image = "~/content/images/Clear_Shade_85_T_Glasses.jpg",
                            Name = "Clear Shade 85-T Glasses",
                            Price = 45m,
                            Qty = 14
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 4,
                            Description = "If you keep your momentum you can charge up pretty much all the climbs and the descents are steep and tricky. Very loose and dry. Narrow in places and twisty througout.",
                            Image = "~/content/images/Cosmic_Elite_Road_Warrior_Wheels.jpg",
                            Name = "Cosmic Elite Road Warrior Wheels",
                            Price = 165m,
                            Qty = 22
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Description = "It has a number of blind LH corners so whistle or use a bell so you can alert anyone coming the opposite way. One of the best rides in all of tahoe.",
                            Image = "~/content/images/Cycle_Doc_Pro_Repair_Stand.jpg",
                            Name = "Cycle-Doc Pro Repair Stand",
                            Price = 166m,
                            Qty = 12
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Description = "From there the trail stretches out and travels pretty fast into a big berm with a view out into the valley. Use caution in the corners. Built specifically for mountain bikes.",
                            Image = "~/content/images/Dog_Ear_Aero_Flow_Floor_Pump.jpg",
                            Name = "Dog Ear Aero-Flow Floor Pump",
                            Price = 55m,
                            Qty = 25
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Description = "features that are designed in a way that uses the rider’s momentum to minimize pedaling and braking (think downhill pump track). Lots of opportunities for big air.",
                            Image = "~/content/images/Dog_Ear_Cycle_Computer.jpg",
                            Name = "Dog Ear Cycle Computer",
                            Price = 75m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            Description = "Winding trail with dips, climbs and descents. Wait a few days after any fresh snowfall and the entire area becomes one giant freeride trail after the shredders pack down the powder.",
                            Image = "~/content/images/Dog_Ear_Helmet_Mount_Mirror.jpg",
                            Name = "Dog Ear Helmet Mount Mirrors",
                            Price = 7.45m,
                            Qty = 12
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 1,
                            Description = "A flow trail emphasizes speed and rhythm, featuring berms, rollers, jumps and other features that are designed in a way that uses the rider’s momentum to minimize pedaling and braking.",
                            Image = "~/content/images/Dog_Ear_Monster_Grip_Gloves.jpg",
                            Name = "Dog Ear Monster Grip Gloves",
                            Price = 15m,
                            Qty = 30
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Description = "16 Mile Summer Trail was initially a rugged singletrack DH trail maintained by local builders since 2008, the State of Alaska installed a more user friendly course in 2012.",
                            Image = "~/content/images/Eagle_FS_3_Mountain_Bike.jpg",
                            Name = "Eagle FS-3 Mountain Bike",
                            Price = 1800m,
                            Qty = 8
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 4,
                            Description = "Formerly smooth as glass, it has taken on a very natural character with lots of rollers to soak up or jump. One of the best rides in all of tahoe.",
                            Image = "~/content/images/Eagle_SA_120_Clipless_Pedals.jpg",
                            Name = "Eagle SA-120 Clipless Pedals",
                            Price = 139.5m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 1,
                            Description = "It is steep. Check your speed before rumbling over the wet armored section that make a tight right hand turn into a bridge. With moderate climbing involved.",
                            Image = "~/content/images/Glide_O_Matic_Cycling_Helmet.jpg",
                            Name = "Glide-O-Matic Cycling Helmet",
                            Price = 125m,
                            Qty = 24
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 2,
                            Description = "These trails can keep almost anyone interested for hours. The route begins at the end of Quid Pro Flow and an intersection with Three Thirty Eight.",
                            Image = "~/content/images/GT_RTS_2_Mountain_Bike.jpg",
                            Name = "GT RTS-2 Mountain Bike",
                            Price = 1650m,
                            Qty = 5
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 1,
                            Description = "MBoSC has partnered with land manager California Department of Forestry and Fire Protection (CAL FIRE) to build a four mile flow trail in Soquel Demonstration State Forest (SDSF).",
                            Image = "~/content/images/HP_Deluxe_Panniers.jpg",
                            Name = "HP Deluxe Panniers",
                            Price = 39m,
                            Qty = 10
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 1,
                            Description = "The area can be accessed from the end of Densmore's Lane, the end of Old Petty Harbour Road and from Huntingdale Drive. One of the best downhills in the area. Pretty dry and fast.",
                            Image = "~/content/images/King_Cobra_Helmet.jpg",
                            Name = "King Cobra Helmet",
                            Price = 139m,
                            Qty = 30
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 4,
                            Description = "There is an optional drop 1/2 way down. On the bike map it is often combined as the Whole Enchilada with Porcupine Rim, Kokopelli, Hazard County and Burro Pass.",
                            Image = "~/content/images/Kool_Breeze_Rocket_Top_Jersey.jpg",
                            Name = "Kool Breeze Rocket Top Jersey",
                            Price = 4.99m,
                            Qty = 40
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 1,
                            Description = "Great conditions today. Large group of trees down on northern section of trail, between buckhorn and club gap. Long pedal up form town but best when shuttled to the top.",
                            Image = "~/content/images/Kryptonite_Advanced_2000_U_Lock.jpg",
                            Name = "Kryptonite Advanced 2000 U-Lock",
                            Price = 50m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 1,
                            Description = "Parking at the bottom is near mile 12 of Palmer Fishhook Road, while the top of the trailhead starts near mile 16 of Palmer Fishhook Road. You can find everyone out here having fun from people.",
                            Image = "~/content/images/Nikoma_Lok_Tight_U_Lock.jpg",
                            Name = "Nikoma Lok-Tight U-Lock",
                            Price = 33m,
                            Qty = 12
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 4,
                            Description = "If you continue, the trail ends at one of the lakes and continues lakeside until reaching the point where you began the trail The lake-side bit is fairly technical and very fun.",
                            Image = "~/content/images/ProFormance_ATB_All_Terrain_Pedal.jpg",
                            Name = "ProFormance ATB All-Terrain Pedal",
                            Price = 28m,
                            Qty = 40
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 4,
                            Description = "Narrow in places and twisty througout, this leg churner is sure to keep you on you toes. The area can be accessed from the end of Densmore's Lane, the end of Old Petty Harbour Road.",
                            Image = "~/content/images/ProFormance_Toe_Klips_2G.jpg",
                            Name = "ProFormance Toe Klips 2G",
                            Price = 28m,
                            Qty = 40
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 1,
                            Description = "This line is my preferred line coming down. 95% dry and/or grippy. Narrow in places and twisty througout, this leg churner is sure to keep you on you toes. This 40+ miles ride is packed full of stunning island views. Sign is posted at entrance.",
                            Image = "~/content/images/Pro_Sport_Dillo_Shades.jpg",
                            Name = "Pro-Sport Dillo Shades",
                            Price = 82m,
                            Qty = 18
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 5,
                            Description = "Amazing views of Castle valley are afforded after 50 meters of riding. Having gotten that out of the way, the Mana Road ride is absolutely beautiful and worth the ride.",
                            Image = "~/content/images/Road_Warrior_Hitch_Pack.jpg",
                            Name = "Road Warrior Hitch Pack",
                            Price = 175m,
                            Qty = 6
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 4,
                            Description = "To the high point just before the intersection with Hooker Creek Trail. Small tree down between bottom of trail and bridge crossing. Technical singletrack. It's mostly a hike-a-bike up and then has an advanced all-mountain feel coming down.",
                            Image = "~/content/images/Shinoman_105_SC_Brakes.jpg",
                            Name = "Shinoman 105 SC Brakes",
                            Price = 23.5m,
                            Qty = 16
                        },
                        new
                        {
                            ProductID = 23,
                            CategoryID = 4,
                            Description = "Amazing views of Castle valley are afforded after 50 meters of riding. From Lake Imaging Road it is a steady but not steep climb to the high point. Built specifically for mountain bikes, a flow trail emphasizes speed and rhythm.",
                            Image = "~/content/images/Shinoman_Deluxe_TX_30_Pedal.jpg",
                            Name = "Shinoman Deluxe TX-30 Pedal",
                            Price = 45m,
                            Qty = 60
                        },
                        new
                        {
                            ProductID = 24,
                            CategoryID = 4,
                            Description = "There is an optional drop 1/2 way down. Small tree down between bottom of trail and bridge crossing. Short and fast, with a few small jumps and some loose rocks. Stay straight when the trail intersects with a doubletrack and then bear left.",
                            Image = "~/content/images/Shinoman_Dura_Ace_Headset.jpg",
                            Name = "Shinoman Dura-Ace Headset",
                            Price = 67.5m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 25,
                            CategoryID = 3,
                            Description = "Other features include rock garden (that is rutted on the outer edges because XC peeps avoid it), skinny with twists and some other short elevated bridges. Brief passing showers are keeping it wet but the sun and wind are trying.",
                            Image = "~/content/images/StaDry_Cycling_Pants.jpg",
                            Name = "StaDry Cycling Pants",
                            Price = 69m,
                            Qty = 22
                        },
                        new
                        {
                            ProductID = 26,
                            CategoryID = 1,
                            Description = "For those that want to get tricksy, there are jumps littered throughout the trail as well. A long, long, did I mention long? Fire road that circles Mauna Kea. It is steep. A full suspension bike with 3+ inches of travel enhance your experience!",
                            Image = "~/content/images/TransPort_Bicycle_Rack.jpg",
                            Name = "TransPort Bicycle Rack",
                            Price = 27m,
                            Qty = 14
                        },
                        new
                        {
                            ProductID = 27,
                            CategoryID = 2,
                            Description = "This 40+ miles ride is packed full of stunning island views. Be warned, this is not for the faint of heart! This ridge is more rugged than the other two ridges. Ride to the top and then down and link it directly into Ridegeline (with some double track).",
                            Image = "~/content/images/Trek_9000_Mountain_Bike.jpg",
                            Name = "Trek 9000 Mountain Bike",
                            Price = 1200m,
                            Qty = 6
                        },
                        new
                        {
                            ProductID = 28,
                            CategoryID = 1,
                            Description = "An awesome descent, with some high speed ripping at the top, some root drops in the middle, and some great bank turns at the bottom. Brief passing showers keep it wet. Parking at the bottom is near mile 12 of Palmer Fishhook Road.",
                            Image = "~/content/images/True_Grip_Competition_Gloves.jpg",
                            Name = "True Grip Competition Gloves",
                            Price = 22m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 29,
                            CategoryID = 6,
                            Description = "The sun and wind are trying. Immediately the trail drops into medium rollers and doubles, winding it's way back down the mountain with steep downhills. Immediately the trail drops into medium rollers and doubles, winding it's way back down the mountain.",
                            Image = "~/content/images/Turbo_Twin_Tires.jpg",
                            Name = "Turbo Twin Tires",
                            Price = 29m,
                            Qty = 18
                        },
                        new
                        {
                            ProductID = 30,
                            CategoryID = 5,
                            Description = "For those that want to get tricksy, there are jumps littered throughout the trail as well. The area can be accessed from the end of Densmore's Lane, the end of Old Petty Harbour Road and from Huntingdale Drive.",
                            Image = "~/content/images/Ultimate_Export_2G_Car_Rack.jpg",
                            Name = "Ultimate Export 2G Car Rack",
                            Price = 180m,
                            Qty = 8
                        },
                        new
                        {
                            ProductID = 31,
                            CategoryID = 6,
                            Description = "While it has no real technical features to speak of since being redesigned, it is a lot of fun to ride this glassy smooth and bermed trail. Kitsuma is a point to point singletrack trail that has a machine groomed tread.",
                            Image = "~/content/images/Ultra_2K_Competition_Tire.jpg",
                            Name = "Ultra-2K Competition Tire",
                            Price = 34m,
                            Qty = 22
                        },
                        new
                        {
                            ProductID = 32,
                            CategoryID = 3,
                            Description = "They can be ridden in the winter depending on snow conditions. Proper sized jumps, berms, rollers and wooden features, so sick! Tree is elevated, so not rideable for most. I discovered this trail while out with my friend one day.",
                            Image = "~/content/images/Ultra_Pro_Rain_Jacket.jpg",
                            Name = "Ultra-Pro Rain Jacket",
                            Price = 85m,
                            Qty = 30
                        },
                        new
                        {
                            ProductID = 33,
                            CategoryID = 6,
                            Description = "Lost Lake starts at its namesake trailhead. Plenty of kick ups, jumps, drops, and huge berms. Yes. Kick ups, jumps, drops, and huge berms. This line is my preferred line coming down. Big downed tree near the end of Lower Black.",
                            Image = "~/content/images/Victoria_Pro_All_Weather_Tires.jpg",
                            Name = "Victoria Pro All Weather Tires",
                            Price = 54.95m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 34,
                            CategoryID = 1,
                            Description = "Or with only moderate climbing involved these trails can keep almost anyone interested for hours. From Lake Imaging Road it is a steady not steep climb. Trails are drying out quickly. There are also several sections of slickrock.",
                            Image = "~/content/images/Viscount_C_500_Wireless_Bike_Computer.jpg",
                            Name = "Viscount C-500 Wireless Bike Computer",
                            Price = 49m,
                            Qty = 30
                        },
                        new
                        {
                            ProductID = 35,
                            CategoryID = 1,
                            Description = "Some wet/muddy creek crossings, but otherwise dry. A super fun freeride trail starting with the Pinkbike drop, an impressive 12' by 12' drop. As the valley begins to close, the route transitions to a section of open forest.",
                            Image = "~/content/images/Viscount_CardioSport_Sport_Watch.jpg",
                            Name = "Viscount CardioSport Sport Watch",
                            Price = 179m,
                            Qty = 12
                        },
                        new
                        {
                            ProductID = 36,
                            CategoryID = 1,
                            Description = "The descents are steep and tricky. The climb to the top ends with a beautiful vista of Twin Lakes and the surrounding area. There was enough rain. It's mostly a hike-a-bike up and then has an advanced all-mountain feel coming down.",
                            Image = "~/content/images/Viscount_Microshell_Helmet.jpg",
                            Name = "Viscount Microshell Helmet",
                            Price = 36m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 37,
                            CategoryID = 2,
                            Description = "It's mostly a hike-a-bike up and then has an advanced all-mountain feel coming down. If you keep your momentum you can charge up all the climbs. The trail ends with some nice berms at the bottom. This line is my preferred line coming down.",
                            Image = "~/content/images/Viscount_Mountain_Bikes.jpg",
                            Name = "Viscount Mountain Bike",
                            Price = 635m,
                            Qty = 5
                        },
                        new
                        {
                            ProductID = 38,
                            CategoryID = 1,
                            Description = "Or those that want to get tricksy, there are jumps littered throughout the trail as well. Trail is in good shape, minus dirt bikers dusting it up some. Sign is posted at entrance to warn userss.",
                            Image = "~/content/images/Viscount_Tru_Beat_Heart_Transmitter.jpg",
                            Name = "Viscount Tru-Beat Heart Transmitter",
                            Price = 47m,
                            Qty = 20
                        },
                        new
                        {
                            ProductID = 39,
                            CategoryID = 3,
                            Description = "Trail contains a rope-suspended ladder bridge, elevated bridges and a long-straight skinny. Then it is a gradual descent or flat on to the end of the trail at Hickory Mountain Road.",
                            Image = "~/content/images/Wonder_Wood_Cycle_Socks.jpg",
                            Name = "Wonder Wool Cycle Socks",
                            Price = 19m,
                            Qty = 30
                        },
                        new
                        {
                            ProductID = 40,
                            CategoryID = 6,
                            Description = "Having gotten that out of the way, the Mana Road ride is absolutely beautiful and worth the ride. Logs embedded in the trail have been installed to signal technical terrain.",
                            Image = "~/content/images/X_Pro_All_Weather_Tires.jpg",
                            Name = "X-Pro All Weather Tires",
                            Price = 24m,
                            Qty = 20
                        });
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorID");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            VendorID = 1,
                            Address = "3042 19th Avenue South",
                            City = "Bellevue",
                            Email = "Sales@Shiniman.com",
                            Name = "Shinoman, Incorporated",
                            PhoneNumber = "425-888-1234",
                            State = "WA",
                            ZipCode = "98001"
                        },
                        new
                        {
                            VendorID = 2,
                            Address = "1911 Commerce Way",
                            City = "St. Louis",
                            Email = "Orders@ViscountBikes.com",
                            Name = "Viscount",
                            PhoneNumber = "314-777-1234",
                            State = "MO",
                            ZipCode = "63127"
                        },
                        new
                        {
                            VendorID = 3,
                            Address = "88 Old North Road Ave",
                            City = "Ballard",
                            Email = "BuyBikes@NikomaBikes.com",
                            Name = "Nikoma of America",
                            PhoneNumber = "206-666-1234",
                            State = "WA",
                            ZipCode = "91324"
                        },
                        new
                        {
                            VendorID = 4,
                            Address = "29 N. Quail St.",
                            City = "Albany",
                            Email = "Sales@ProFormBikes.com",
                            Name = "ProFormance",
                            PhoneNumber = "518-444-1234",
                            State = "NY",
                            ZipCode = "12012"
                        },
                        new
                        {
                            VendorID = 5,
                            Address = "PO Box 10429",
                            City = "Redmond",
                            Email = "Sales@KonaBikes.com",
                            Name = "Kona, Incorporated",
                            PhoneNumber = "425-333-1234",
                            State = "WA",
                            ZipCode = "98052"
                        },
                        new
                        {
                            VendorID = 6,
                            Address = "Glacier Bay South",
                            City = "Anchorage",
                            Email = "Sales@BigSkyBikes.com",
                            Name = "Big Sky Mountain Bikes",
                            PhoneNumber = "907-222-1234",
                            State = "AK",
                            ZipCode = "99209"
                        },
                        new
                        {
                            VendorID = 7,
                            Address = "575 Madison Ave.",
                            City = "New York",
                            Email = "Sales@DogEar.com",
                            Name = "Dog Ear",
                            PhoneNumber = "212-888-9876",
                            State = "NY",
                            ZipCode = "10003"
                        },
                        new
                        {
                            VendorID = 8,
                            Address = "PO Box 8082",
                            City = "Santa Monica",
                            Email = "Sales@SunSports.com",
                            Name = "Sun Sports Suppliers",
                            PhoneNumber = "310-777-9876",
                            State = "CA",
                            ZipCode = "91003"
                        },
                        new
                        {
                            VendorID = 9,
                            Address = "7402 Kingman Drive",
                            City = "El Paso",
                            Email = "Sales@LoneStarBikes.com",
                            Name = "Lone Star Bike Supply",
                            PhoneNumber = "915-666-9876",
                            State = "TX",
                            ZipCode = "79915"
                        },
                        new
                        {
                            VendorID = 10,
                            Address = "12330 Side Road Lane",
                            City = "Dallas",
                            Email = "BikeProducts@DilloBikes.com",
                            Name = "Armadillo Brand",
                            PhoneNumber = "214-444-9876",
                            State = "TX",
                            ZipCode = "75137"
                        });
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Product", b =>
                {
                    b.HasOne("BikeShop_HOT.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BikeShop_HOT.Models.Category", b =>
                {
                    b.Navigation("CategoryProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
