INSERT INTO Categories (CategoryDescription)
  VALUES ('Accessories');
INSERT INTO Categories (CategoryDescription)
  VALUES ('Bikes');
INSERT INTO Categories (CategoryDescription)
  VALUES ('Clothing');
INSERT INTO Categories (CategoryDescription)
  VALUES ('Components');
INSERT INTO Categories (CategoryDescription)
  VALUES ('Car racks');
INSERT INTO Categories (CategoryDescription)
  VALUES ('Wheels');
