INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Suzanne', 'Viescas', '15127 NE 24th, #383', 
   'Redmond', 'WA', '98052', 425, '555-2686');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('William', 'Thompson', '122 Spring River Drive', 
   'Duvall', 'WA', '98019', 425, '555-2681');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Gary', 'Hallmark', 'Route 2, Box 203B', 
   'Auburn', 'WA', '98002', 253, '555-2676');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Robert', 'Brown', '672 Lamont Ave', 
   'Houston', 'TX', '77201', 713, '555-2491');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Dean', 'McCrae', '4110 Old Redmond Rd.', 
   'Redmond', 'WA', '98052', 425, '555-2506');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('John', 'Viescas', '15127 NE 24th, #383', 
   'Redmond', 'WA', '98052', 425, '555-2511');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Mariya', 'Sergienko', '901 Pine Avenue', 
   'Portland', 'OR', '97208', 503, '555-2526');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Neil', 'Patterson', '233 West Valley Hwy', 
   'San Diego', 'CA', '92199', 619, '555-2541');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Andrew', 'Cencini', '507 - 20th Ave. E.
Apt. 2A', 'Seattle', 'WA', '98105', 206, '555-2601');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Angel', 'Kennedy', '667 Red River Road', 
   'Austin', 'TX', '78710', 512, '555-2571');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Alaina', 'Hallmark', 'Route 2, Box 203B', 
   'Woodinville', 'WA', '98072', 425, '555-2631');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Liz', 'Keyser', '13920 S.E. 40th Street', 
   'Bellevue', 'WA', '98006', 425, '555-2556');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Rachel', 'Patterson', '2114 Longview Lane', 
   'San Diego', 'CA', '92199', 619, '555-2546');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Sam', 'Abolrous', '611 Alpine Drive', 
   'Palm Springs', 'CA', '92263', 760, '555-2611');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Darren', 'Gehring', '2601 Seaview Lane', 
   'Chico', 'CA', '95926', 530, '555-2616');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Jim', 'Wilson', '101 NE 88th', 'Salem', 
   'OR', '97301', 503, '555-2636');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Manuela', 'Seidel', '66 Spring Valley Drive', 
   'Medford', 'OR', '97501', 541, '555-2641');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('David', 'Smith', '311 20th Ave. N.E.', 
   'Fremont', 'CA', '94538', 510, '555-2646');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Zachary', 'Ehrlich', '12330 Kingman Drive', 
   'Glendale', 'CA', '91209', 818, '555-2721');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Joyce', 'Bonnicksen', '2424 Thames Drive', 
   'Bellevue', 'WA', '98006', 425, '555-2726');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Estella', 'Pundt', '2500 Rosales Lane', 
   'Dallas', 'TX', '75260', 972, '555-9938');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Caleb', 'Viescas', '4501 Wetland Road', 
   'Long Beach', 'CA', '90809', 562, '555-0037');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Julia', 'Schnebly', '2343 Harmony Lane', 
   'Seattle', 'WA', '99837', 206, '555-9936');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Mark', 'Rosales', '323 Advocate Lane', 
   'El Paso', 'TX', '79915', 915, '555-2286');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Maria', 'Patterson', '3445 Cheyenne Road', 
   'El Paso', 'TX', '79915', 915, '555-2291');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Kirk', 'DeGrasse', '455 West Palm Ave', 
   'San Antonio', 'TX', '78284', 210, '555-2311');
INSERT INTO Customers  (CustomerFirstName, CustomerLastName,
						CustomerStreetAddress, CustomerCity,
						CustomerState, CustomerZipCode,
						CustomerAreaCode, CustomerPhoneNumber)
  VALUES ('Luke', 'Patterson', '877 145th Ave SE', 
   'Portland', 'OR', '97208', 503, '555-2316');
