INSERT INTO Employees  (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Ann', 'Patterson', '16 Maple Lane', 
   'Auburn', 'WA', '98002', 253, '555-2591');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Mary', 'Thompson', '122 Spring River Drive', 
   'Duvall', 'WA', '98019', 425, '555-2516');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Matt', 'Berg', '908 W. Capital Way', 
   'Tacoma', 'WA', '98413', 253, '555-2581');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Carol', 'Viescas', '722 Moss Bay Blvd.', 
   'Kirkland', 'WA', '98033', 425, '555-2576');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Kirk', 'DeGrasse', '455 West Palm Ave', 
   'San Antonio', 'TX', '78284', 210, '5552311');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('David', 'Viescas', '16679 NE 42nd Court', 
   'Redmond', 'WA', '98052', 425, '555-2661');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Kathryn', 'Patterson', '554 E. Wilshire
Apt. 2A', 
   'Seattle', 'WA', '98105', 206, '555-2697');
INSERT INTO Employees (EmployeeFirstName, EmployeeLastName,
						EmployeeStreetAddress,
						EmployeeCity, EmployeeState, EmployeeZipCode,
						EmployeeAreaCode, EmployeePhoneNumber)
  VALUES ('Susan', 'McLain', '511 Lenora Ave', 
   'Bellevue', 'WA', '98006', 425, '555-2301');
