INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Shinoman, Incorporated', '3042 19th Avenue South', 
   'Bellevue', 'WA', '98001', '(425) 888-1234', '(425) 888-1235', 
   '#http://www.shinoman.com/#', 'Sales@Shiniman.com');
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Viscount', '1911 Commerce Way', 'St. Louis', 
   'MO', '63127', '(314) 777-1234', '(314) 777-1235', 
   '#http://www.viscountbikes.com/#', 'Orders@ViscountBikes.com');
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Nikoma of America', '88 Old North Road Ave', 
   'Ballard', 'WA', '91324', '(206) 666-1234', '(314) 666-1235', 
   '#http://www.nikomabikes.com/#', 'BuyBikes@NikomaBikes.com');
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('ProFormance', '29 N. Quail St.', 'Albany', 
   'NY', '12012', '(518) 444-1234', '(518) 444-1235', 
   '#http://www.ProFormBikes.com/#', 'Sales@ProFormBikes.com');
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Kona, Incorporated', 'PO Box 10429', 
   'Redmond', 'WA', '98052', '(425) 333-1234', '(425) 333-1235', 
   '#http://www.konabikes.com/#', 'Sales@KonaBikes.com');
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Big Sky Mountain Bikes', 'Glacier Bay South', 
   'Anchorage', 'AK', '99209', '(907) 222-1234', '(907) 222-1235', 
   NULL, NULL);
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Dog Ear', '575 Madison Ave.', 'New York', 
   'NY', '10003', '(212) 888-9876', '(212) 888-9877', 
   NULL, NULL);
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Sun Sports Suppliers', 'PO Box 8082', 
   'Santa Monica', 'CA', '91003', '(310) 777-9876', 
   '(310) 777-9877', NULL, NULL);
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Lone Star Bike Supply', '7402 Kingman Drive', 
   'El Paso', 'TX', '79915', '(915) 666-9876', '(915) 666-9877', 
   NULL, NULL);
INSERT INTO Vendors (VendorName, VendorStreetAddress,
					 VendorCity, VendorState, VendorZipCode,
					 VendorPhoneNumber, VendorFaxNumber,
					 VendorWebPage, VendorEmailAddress)
  VALUES ('Armadillo Brand', '12330 Side Road Lane', 
   'Dallas', 'TX', '75137', '(214) 444-9876', '(214) 444-9877', 
   '#http://www.DilloBikes.com/#', 'BikeProducts@DilloBikes.com');
