INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('AeroFlo ATB Wheels', NULL,  NULL,
'~/content/images/01-AeroFlo-ATB-Wheels.jpg',
189, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Clear Shade 85-T Glasses', NULL, NULL,
'~/content/images/02-Clear-Shade-85-T-Glasses.jpg',
45, 14, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Cosmic Elite Road Warrior Wheels', NULL, NULL,
'~/content/images/03-Cosmic-Elite-Road-Warrior-Wheels.jpg',
165, 22, 4);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Cycle-Doc Pro Repair Stand', NULL, NULL,
'~/content/images/04-Cycle-Doc-Pro-Repair-Stand.jpg',
166, 12, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Aero-Flow Floor Pump', NULL, NULL,
'~/content/images/05-Dog-Ear-Aero-Flow-Floor-Pump.jpg',
55, 25, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Cycle Computer', NULL, NULL,
'~/content/images/06-Dog-Ear-Cycle-Computer.jpg',
75, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Dog Ear Helmet Mount Mirrors', NULL, NULL,
'~/content/images/07-Dog-Ear-Helmet-Mount-Mirror.jpg',
7.45, 12, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Dog Ear Monster Grip Gloves', NULL, NULL,
'~/content/images/08-Dog-Ear-Monster-Grip-Gloves.jpg',
15, 30, 1);
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Eagle FS-3 Mountain Bike', NULL, NULL,
'~/content/images/09-Eagle-FS-3-Mountain-Bike.jpg',
1800, 8, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Eagle SA-120 Clipless Pedals', NULL, NULL,
'~/content/images/10-Eagle-SA-120-Clipless-Pedals.jpg',
139.95, 20, 4); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Glide-O-Matic Cycling Helmet', NULL, NULL,
'~/content/images/11-Glide-O-Matic-Cycling-Helmet.jpg',
125, 24, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('GT RTS-2 Mountain Bike', NULL, NULL,
'~/content/images/12-GT-RTS-2-Mountain-Bike.jpg',
1650, 5, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('HP Deluxe Panniers', NULL, NULL,
'~/content/images/13-HP-Deluxe-Panniers.jpg',
39, 10, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('King Cobra Helmet', NULL, NULL,
'~/content/images/14-King-Cobra-Helmet.jpg',
139, 30, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Kool Breeze Rocket Top Jersey', NULL, NULL,
'~/content/images/15-Kool-Breeze-Rocket-Top-Jersey.jpg',
4.99, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Kryptonite Advanced 2000 U-Lock', NULL, NULL, 
'~/content/images/16-Kryptonite-Advanced-2000-U-Lock.jpg',
50, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Nikoma Lok-Tight U-Lock', NULL, NULL,
'~/content/images/17-Nikoma-Lok-Tight-U-Lock.jpg',
33, 12, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('ProFormance ATB All-Terrain Pedal', NULL, NULL,
'~/content/images/18-ProFormance-ATB-All-Terrain-Pedal.jpg',
28, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('ProFormance Toe Klips 2G', NULL, NULL,
'~/content/images/19-ProFormance-Toe-Klips-2G.jpg',
28, 40, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Pro-Sport Dillo Shades', NULL, NULL,
'~/content/images/20-Pro-Sport-Dillo-Shades.jpg',
82, 18, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Road Warrior Hitch Pack', NULL,  NULL,
'~/content/images/21-Road-Warrior-Hitch-Pack.jpg',
175, 6, 5); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Shinoman 105 SC Brakes', NULL, NULL,
'~/content/images/22-Shinoman-105-SC-Brakes.jpg',
23.5, 16, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('Shinoman Deluxe TX-30 Pedal', NULL, NULL,
'~/content/images/23-Shinoman-Deluxe-TX-30-Pedal.jpg',
45, 60, 4);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Shinoman Dura-Ace Headset', NULL, NULL,
'~/content/images/24-Shinoman-Dura-Ace-Headset.jpg',
67.5, 20, 4); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('StaDry Cycling Pants', NULL, NULL,
'~/content/images/25-StaDry-Cycling-Pants.jpg',
69, 22, 3);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
 VALUES ('TransPort Bicycle Rack', NULL, NULL,
'~/content/images/26-TransPort-Bicycle-Rack.jpg',
27, 14, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Trek 9000 Mountain Bike', NULL, NULL,
'~/content/images/27-Trek-9000-Mountain-Bike.jpg',
1200, 6, 2); 
 
INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('True Grip Competition Gloves', NULL, NULL,
'~/content/images/28-True-Grip-Competition-Gloves.jpg',
22, 20, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Turbo Twin Tires', NULL, NULL,
'~/content/images/29-Turbo-Twin-Tires.jpg',
29, 18, 6);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultimate Export 2G Car Rack', NULL,  NULL, 
'~/content/images/30-Ultimate-Export-2G-Car-Rack.jpg',
180, 8, 5);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultra-2K Competition Tire', NULL, NULL,
'~/content/images/31-Ultra-2K-Competition-Tire.jpg',
34, 22, 6);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Ultra-Pro Rain Jacket', NULL, NULL,
'~/content/images/32-Ultra-Pro-Rain-Jacket.jpg',
85, 30, 3); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Victoria Pro All Weather Tires', NULL, NULL,
'~/content/images/33-Victoria-Pro-All-Weather-Tires.jpg',
54.95, 20, 4); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount C-500 Wireless Bike Computer', NULL, NULL,
'~/content/images/34-Viscount-C-500-Wireless-Bike-Computer.jpg',
49, 30, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount CardioSport Sport Watch', NULL, NULL,
'~/content/images/35-Viscount-CardioSport-Sport-Watch.jpg',
179, 12, 1); 

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Microshell Helmet', NULL, NULL,
'~/content/images/36-Viscount-Microshell-Helmet.jpg',
36, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Mountain Bike', NULL, NULL,
'~/content/images/37-Viscount-Mountain-Bikes.jpg',
635, 5, 2);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Viscount Tru-Beat Heart Transmitter', NULL, NULL,
'~/content/images/38-Viscount-Tru-Beat-Heart-Transmitter.jpg',
47, 20, 1);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('Wonder Wool Cycle Socks', NULL, NULL,
'~/content/images/39-Wonder-Wood-Cycle-Socks.jpg',
19, 30, 3);

INSERT INTO Products
(ProductName, 		ProductDescShort, 
 ProductDescLong, 	ProductImage, 
 ProductPrice, 		ProductQty, CategoryID)
VALUES ('X-Pro All Weather Tires', NULL, NULL,
'~/content/images/40-X-Pro-All-Weather-Tires.jpg',
24, 20, 6);