INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (1, 4, 804, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (1, 9, 854.22, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (2, 6, 1269, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (2, 9, 1477.81, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (3, 7, 54.19, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (3, 9, 57.27, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (4, 6, 44.22, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (4, 9, 41.62, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (5, 7, 5.38, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (5, 9, 5.87, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (6, 2, 403.22, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (6, 9, 448.73, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (7, 2, 31.12, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (8, 8, 39.32, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (8, 9, 37.88, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (9, 3, 21.53, 4);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (10, 2, 22.86, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (11, 3, 1076.62, 4);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (11, 9, 1178.65, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (12, 1, 14.51, 2);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (12, 6, 15.44, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (12, 9, 15.02, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (13, 1, 41.68, 2);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (13, 6, 43.99, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (13, 9, 43.77, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (14, 6, 98.66, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (14, 9, 101.22, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (15, 4, 3.34, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (15, 6, 3.79, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (15, 9, 3.88, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (16, 4, 18.76, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (16, 6, 19.33, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (16, 9, 19.33, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (17, 1, 27.79, 2);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (17, 6, 28.55, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (17, 9, 28.55, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (18, 2, 113.66, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (19, 2, 29.84, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (20, 7, 10.84, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (20, 9, 11.54, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (21, 7, 39.74, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (21, 9, 41.5, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (22, 10, 63.55, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (23, 6, 69.54, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (23, 9, 64.39, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (24, 6, 55.91, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (24, 7, 53.88, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (24, 9, 52.27, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (25, 9, 105.29, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (25, 10, 101.58, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (26, 3, 81.56, 4);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (26, 6, 79.88, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (27, 3, 15.66, 4);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (27, 6, 16.88, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (27, 9, 15.88, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (28, 3, 18.92, 4);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (28, 6, 20.56, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (28, 9, 19.04, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (29, 5, 23.38, 8);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (29, 6, 24.44, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (29, 9, 23.99, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (30, 8, 33.3, 12);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (30, 9, 35.32, 8);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (30, 10, 32.87, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (31, 7, 15.85, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (31, 8, 16.28, 12);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (31, 9, 16.93, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (31, 10, 16.9, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (32, 6, 24.77, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (32, 7, 24.12, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (32, 8, 23.68, 12);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (33, 6, 15.23, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (33, 8, 14.06, 12);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (34, 6, 19.04, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (34, 9, 23.86, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (34, 10, 19.32, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (35, 6, 27.49, 9);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (35, 9, 28.22, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (36, 6, 122.88, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (36, 7, 119.21, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (36, 9, 122.78, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (37, 2, 120.02, 3);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (37, 6, 125.99, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (37, 9, 124.89, 14);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (38, 9, 136.98, 6);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (38, 10, 128.65, 15);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (39, 6, 137.55, 7);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (39, 7, 126.44, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (40, 6, 154.87, 10);
INSERT INTO ProductVendors (ProductID , VendorID,
							 ProductVendorWholesalePrice, ProductVendorDaysToDeliver)
  VALUES (40, 9, 136.35, 14);
