INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-04', 1018, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-03', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-04', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-03', 1009, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-01', 1024, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-05', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-04', 1001, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-01', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-04', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-01', '2023-09-04', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-04', 1020, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-05', 1024, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-02', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-03', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-06', 1004, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-06', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-03', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-03', 1016, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-06', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-02', '2023-09-02', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-03', '2023-09-03', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-03', '2023-09-07', 1026, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-03', '2023-09-04', 1017, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-03', '2023-09-05', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-03', '2023-09-04', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-04', '2023-09-08', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-04', '2023-09-05', 1014, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-04', '2023-09-08', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-04', '2023-09-08', 1015, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-04', '2023-09-08', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-05', '2023-09-09', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-05', '2023-09-09', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-05', '2023-09-06', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-06', '2023-09-07', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-06', '2023-09-06', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-06', '2023-09-07', 1007, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-11', 1027, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-11', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-10', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-07', 1017, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-07', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-10', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-11', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-07', '2023-09-08', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-08', 1008, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-09', 1018, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-10', 1023, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-11', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-08', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-12', 1002, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-08', '2023-09-08', 1018, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-11', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-09', 1004, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-09', 1007, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-11', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-12', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-10', 1009, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-13', 1006, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-09', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-13', 1013, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-09', '2023-09-10', 1009, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-13', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-13', 1023, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-14', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-13', 1021, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-11', 1026, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-10', '2023-09-11', 1025, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-11', '2023-09-12', 1027, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-11', '2023-09-13', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-16', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-14', 1016, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-16', 1003, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-15', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-13', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-14', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-15', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-12', '2023-09-13', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-16', 1007, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-17', 1006, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-16', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-13', 1006, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-16', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-16', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-13', 1022, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-15', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-16', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-13', '2023-09-14', 1002, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-17', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-17', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-15', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-18', 1010, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-17', 1011, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-17', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-14', '2023-09-14', 1010, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-19', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-16', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-18', 1026, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-16', 1009, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-18', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ( '2023-09-15', '2023-09-16', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-18', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-17', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-16', 1025, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-15', '2023-09-15', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-16', '2023-09-18', 1005, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-16', '2023-09-20', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-16', '2023-09-20', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-16', '2023-09-19', 1004, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-16', '2023-09-16', 1013, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-17', '2023-09-19', 1015, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-17', '2023-09-21', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-18', '2023-09-19', 1009, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-18', '2023-09-22', 1010, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-18', '2023-09-22', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-19', '2023-09-21', 1003, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-19', '2023-09-21', 1004, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-22', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-22', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-20', 1013, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-21', 1024, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-21', 1025, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-24', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-20', '2023-09-22', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-21', '2023-09-23', 1007, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-21', '2023-09-21', 1011, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-24', 1016, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-25', 1009, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-26', 1022, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-22', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-24', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-22', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-25', 1007, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-22', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-22', '2023-09-24', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-23', '2023-09-26', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-23', '2023-09-26', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-23', '2023-09-23', 1001, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-24', '2023-09-27', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-24', '2023-09-26', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-24', '2023-09-24', 1002, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-24', '2023-09-27', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-25', '2023-09-29', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-25', '2023-09-28', 1021, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-25', '2023-09-29', 1018, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-26', '2023-09-30', 1027, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-26', '2023-09-26', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-26', '2023-09-26', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-26', '2023-09-30', 1027, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-27', '2023-09-28', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-27', '2023-09-27', 1024, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-27', '2023-09-28', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-28', '2023-10-02', 1017, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-09-30', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-10-02', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-10-03', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-09-30', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-10-01', 1010, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-10-03', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-29', '2023-10-03', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-30', '2023-09-30', 1021, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-30', '2023-09-30', 1011, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-30', '2023-10-01', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-09-30', '2023-09-30', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-01', '2023-10-04', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-02', '2023-10-02', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-03', '2023-10-06', 1022, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-03', '2023-10-03', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-03', '2023-10-05', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-03', '2023-10-06', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-04', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-05', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-07', 1018, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-04', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-08', 1006, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-07', 1013, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-04', 1025, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-08', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-07', 1022, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-04', '2023-10-08', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-08', 1015, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-05', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-06', 1002, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-05', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-09', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-09', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-05', '2023-10-05', 1002, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-07', 1022, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-07', 1002, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-07', 1012, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-10', 1024, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-07', 1015, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-09', 1022, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-06', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-06', '2023-10-08', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-10', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-11', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-10', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-09', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-09', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-08', 1026, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-08', 1018, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-07', '2023-10-09', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-08', '2023-10-08', 1023, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-08', '2023-10-08', 1026, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-08', '2023-10-12', 1006, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-08', '2023-10-12', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-08', '2023-10-10', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-09', '2023-10-11', 1019, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-10', '2023-10-11', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-10', '2023-10-12', 1024, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-10', '2023-10-13', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-10', '2023-10-11', 1007, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-11', '2023-10-12', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-11', '2023-10-11', 1021, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-11', '2023-10-11', 1002, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-11', '2023-10-11', 1016, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-14', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-15', 1014, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-13', 1018, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-14', 1014, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-14', 1008, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-16', 1007, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-15', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-12', '2023-10-15', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-13', '2023-10-13', 1017, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-13', '2023-10-15', 1023, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-14', '2023-10-17', 1006, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-15', '2023-10-15', 1017, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-15', '2023-10-18', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-15', '2023-10-19', 1008, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-15', '2023-10-17', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-15', '2023-10-16', 1017, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-16', '2023-10-18', 1014, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-16', '2023-10-19', 1010, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-16', '2023-10-19', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-17', '2023-10-19', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-17', '2023-10-19', 1027, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-17', '2023-10-20', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-17', '2023-10-18', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-18', 1022, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-18', 1008, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-20', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-21', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-21', 1014, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-18', '2023-10-19', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-22', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-22', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-20', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-22', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-21', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-22', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-19', '2023-10-20', 1010, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-20', '2023-10-20', 1024, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-21', '2023-10-25', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-21', '2023-10-21', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-21', '2023-10-21', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-21', '2023-10-21', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-22', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-22', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-22', 1006, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-26', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-24', 1020, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-25', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-22', 1002, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-25', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-26', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-22', '2023-10-23', 1004, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-23', '2023-10-24', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-23', '2023-10-24', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-23', '2023-10-26', 1007, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-24', 1010, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-26', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-24', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-26', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-28', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-24', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-24', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-24', '2023-10-25', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-25', '2023-10-29', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-25', '2023-10-27', 1016, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-25', '2023-10-27', 1006, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-28', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-27', 1015, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-30', 1016, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-27', 1024, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-27', 1019, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-29', 1018, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-26', '2023-10-30', 1027, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-27', '2023-10-31', 1002, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-28', '2023-10-28', 1018, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-28', '2023-11-01', 1025, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-28', '2023-10-28', 1013, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-28', '2023-10-29', 1025, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-29', '2023-10-30', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-29', '2023-10-29', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-29', '2023-10-29', 1014, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-29', '2023-11-01', 1008, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-29', '2023-11-01', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-30', '2023-11-03', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-30', '2023-10-30', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-30', '2023-11-03', 1025, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-30', '2023-11-01', 1007, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-03', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-04', 1015, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-04', 1013, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-02', 1026, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-01', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-01', 1002, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-03', 1020, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-10-31', '2023-11-02', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-03', 1003, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-01', 1003, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-01', 1024, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-03', 1007, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-05', 1024, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-05', 1018, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-01', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-01', '2023-11-02', 1024, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-03', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-06', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-04', 1011, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-03', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-04', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-03', 1016, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-03', 1002, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-06', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-02', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-02', '2023-11-05', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-03', '2023-11-05', 1004, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-03', '2023-11-06', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-03', '2023-11-05', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-04', '2023-11-04', 1006, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-04', '2023-11-06', 1003, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-04', '2023-11-08', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-04', '2023-11-05', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-05', '2023-11-06', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-05', '2023-11-06', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-05', '2023-11-05', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-05', '2023-11-09', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-05', '2023-11-09', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-06', '2023-11-07', 1022, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-07', '2023-11-09', 1013, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-07', '2023-11-10', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-07', '2023-11-11', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-07', '2023-11-10', 1008, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-07', '2023-11-11', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-08', '2023-11-08', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-08', '2023-11-10', 1015, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-08', '2023-11-09', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-08', '2023-11-10', 1019, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-09', '2023-11-13', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-09', '2023-11-10', 1020, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-09', '2023-11-13', 1026, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-10', '2023-11-11', 1021, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-10', '2023-11-11', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-10', '2023-11-14', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-10', '2023-11-12', 1003, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-10', '2023-11-14', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-13', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1010, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-14', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-12', 1004, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-11', '2023-11-11', 1011, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-13', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-13', 1003, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-12', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-15', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-14', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-15', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-12', '2023-11-12', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-15', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-13', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-17', 1019, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-14', 1014, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-17', 1025, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-13', '2023-11-16', 1023, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-14', '2023-11-16', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-15', '2023-11-15', 1017, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-16', '2023-11-19', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-16', '2023-11-16', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-20', 1019, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-17', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-21', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-21', 1008, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-20', 1005, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-20', 1016, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-17', 1024, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-17', '2023-11-21', 1006, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-18', '2023-11-20', 1011, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-18', '2023-11-21', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-19', '2023-11-23', 1014, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-19', '2023-11-20', 1019, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-19', '2023-11-19', 1020, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-22', 1004, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-23', 1007, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-24', 1026, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-21', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-22', 1017, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-20', 1006, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-21', 1019, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-20', '2023-11-23', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-21', '2023-11-25', 1012, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-22', '2023-11-25', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-23', '2023-11-27', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-23', '2023-11-24', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-23', '2023-11-24', 1008, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-25', 1002, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-27', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-25', 1001, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-28', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-27', 1013, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-25', 1024, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-27', 1017, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-24', '2023-11-24', 1012, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-25', 1006, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-25', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-28', 1022, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-26', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-29', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-25', '2023-11-27', 1025, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-30', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-29', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-29', 1020, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-27', 1024, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-29', 1016, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-26', '2023-11-30', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-30', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-30', 1022, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-27', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-29', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-29', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-30', 1014, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-11-29', 1002, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-27', '2023-12-01', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-28', '2023-12-02', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-28', '2023-11-29', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-28', '2023-11-28', 1010, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-28', '2023-12-01', 1002, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-12-02', 1001, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-11-30', 1002, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-11-30', 1007, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-12-03', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-11-30', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-12-01', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-29', '2023-11-29', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-04', 1004, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-02', 1003, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-02', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-04', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-02', 1010, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-11-30', '2023-12-01', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-01', '2023-12-02', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-01', '2023-12-05', 1019, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-02', '2023-12-02', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-02', '2023-12-03', 1007, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-03', '2023-12-05', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-03', '2023-12-07', 1021, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-03', '2023-12-03', 1004, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-04', '2023-12-07', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ( '2023-12-04', '2023-12-07', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-04', '2023-12-04', 1012, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-06', 1026, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-05', 1013, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-06', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-05', 1011, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-08', 1014, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-07', 1025, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-09', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-08', 1016, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-05', '2023-12-08', 1006, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-10', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-10', 1014, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-06', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-10', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-09', 1024, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-06', '2023-12-06', 1011, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-07', '2023-12-10', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-07', '2023-12-07', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-07', '2023-12-08', 1005, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-09', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-10', 1003, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-09', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-10', 1009, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-10', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-08', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-10', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-08', '2023-12-09', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-09', '2023-12-11', 1008, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-09', '2023-12-13', 1005, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-09', '2023-12-13', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-09', '2023-12-10', 1012, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-10', '2023-12-10', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-10', '2023-12-11', 1002, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-10', '2023-12-12', 1018, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-10', '2023-12-14', 1016, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-10', '2023-12-10', 1007, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-14', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-14', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-13', 1026, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-14', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-15', 1006, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-13', 1016, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-11', 1017, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-11', '2023-12-14', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-13', 1010, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-13', 1015, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-12', 1026, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-14', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-15', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-14', 1025, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-15', 1003, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-12', '2023-12-16', 1021, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-15', 1007, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-14', 1007, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-15', 1018, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-17', 1027, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-17', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-13', '2023-12-17', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-14', '2023-12-16', 1003, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-15', '2023-12-19', 1002, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-15', '2023-12-18', 1019, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-15', '2023-12-18', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-15', '2023-12-19', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-16', '2023-12-17', 1026, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-16', '2023-12-18', 1013, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-16', '2023-12-18', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-16', '2023-12-16', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-18', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-20', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-17', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-18', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-20', 1020, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-17', '2023-12-20', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-18', '2023-12-19', 1008, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-19', '2023-12-23', 1008, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-19', '2023-12-23', 1007, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-20', '2023-12-22', 1006, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-24', 1008, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-24', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-21', 1009, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-25', 1010, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-21', 1013, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-21', 1011, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-23', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-21', '2023-12-21', 1024, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-22', '2023-12-24', 1003, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-27', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-26', 1023, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-27', 1002, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-24', 1002, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-26', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-27', 1019, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-23', '2023-12-23', 1026, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-25', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-26', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-28', 1016, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-27', 1025, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-27', 1006, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-25', 1020, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-24', '2023-12-26', 1001, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-27', 1014, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-26', 1007, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-27', 1001, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-26', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-27', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-25', '2023-12-29', 1022, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-26', '2023-12-29', 1019, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-26', '2023-12-26', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-26', '2023-12-28', 1019, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-26', '2023-12-26', 1003, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-26', '2023-12-30', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-27', '2023-12-27', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-27', '2023-12-27', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-27', '2023-12-28', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-27', '2023-12-31', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-27', '2023-12-27', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-28', '2023-12-28', 1003, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-28', '2023-12-31', 1004, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-28', '2023-12-28', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2023-12-31', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2023-12-29', 1009, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2023-12-30', 1023, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2021-01-02', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2023-12-29', 1003, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2023-12-29', 1013, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-29', '2021-01-02', 1018, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-30', '2021-01-02', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-30', '2021-01-01', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-30', '2021-01-02', 1026, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-30', '2023-12-30', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-31', '2021-01-03', 1015, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-31', '2021-01-04', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-31', '2023-12-31', 1006, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2023-12-31', '2021-01-01', 1013, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-01', 1011, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-05', 1006, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-02', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-05', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-03', 1015, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-02', 1006, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-01', '2021-01-02', 1020, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-03', 1007, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-05', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-06', 1001, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-06', 1017, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-02', 1020, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-04', 1005, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-02', '2021-01-03', 1005, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-03', '2021-01-05', 1015, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-04', '2021-01-05', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-06', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-06', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-05', 1012, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-09', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-06', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-07', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-05', '2021-01-08', 1007, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-06', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-08', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-09', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-08', 1006, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-10', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-08', 1027, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-06', '2021-01-07', 1026, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-11', 1014, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-09', 1026, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-07', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-11', 1001, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-09', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-11', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-10', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-10', 1002, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-10', 1008, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-07', '2021-01-09', 1003, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-10', 1019, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-11', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-11', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-10', 1012, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-11', 1011, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-09', 1021, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-12', 1024, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-08', '2021-01-09', 1017, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-09', '2021-01-13', 1014, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-09', '2021-01-10', 1015, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-09', '2021-01-13', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-09', '2021-01-09', 1005, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-09', '2021-01-12', 1025, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-10', 1024, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-13', 1015, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-14', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-14', 1007, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-10', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-13', 1001, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-10', 1010, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-10', '2021-01-12', 1023, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-14', 1027, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-15', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-13', 1006, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-14', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-11', 1015, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-11', 1020, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-13', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-14', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-14', 1018, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-11', '2021-01-14', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-16', 1021, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-12', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-15', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-12', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-12', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-13', 1016, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-12', '2021-01-15', 1002, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-16', 1005, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-16', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-14', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-16', 1013, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-14', 1015, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-15', 1018, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-13', '2021-01-13', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-17', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-15', 1005, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-18', 1026, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-16', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-18', 1002, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-15', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-14', 1016, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-14', '2021-01-18', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-18', 1019, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-18', 1002, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-16', 1019, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-17', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-16', 1002, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-15', '2021-01-15', 1005, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-16', '2021-01-17', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-18', 1013, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-17', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-19', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-20', 1020, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-19', 1007, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-21', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-20', 1015, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-17', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-17', '2021-01-18', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-18', '2021-01-21', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-18', '2021-01-18', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-21', 1007, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-21', 1019, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-22', 1024, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-23', 1007, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-23', 1019, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-19', '2021-01-23', 1020, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-20', '2021-01-24', 1016, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-20', '2021-01-20', 1008, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-20', '2021-01-21', 1010, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-20', '2021-01-23', 1027, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-21', '2021-01-25', 1010, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-21', '2021-01-22', 1015, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-21', '2021-01-22', 1006, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-21', '2021-01-24', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-22', 1017, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-24', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-26', 1015, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-23', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-24', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-24', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-24', 1023, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-22', '2021-01-26', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-23', '2021-01-25', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-23', '2021-01-24', 1011, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-26', 1016, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-24', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-28', 1003, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-27', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-26', 1017, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-24', '2021-01-25', 1022, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-26', 1011, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-25', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-28', 1013, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-27', 1008, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-28', 1027, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-29', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-29', 1013, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-28', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-28', 1021, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-25', '2021-01-29', 1021, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-26', '2021-01-30', 1018, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-26', '2021-01-30', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-27', '2021-01-31', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-27', '2021-01-29', 1013, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-27', '2021-01-31', 1014, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-31', 1010, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-28', 1005, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-30', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-30', 1020, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-28', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-28', '2021-01-31', 1014, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-01-30', 1016, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-02-02', 1013, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-02-01', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-01-29', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-01-31', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-29', '2021-01-30', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-01-31', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-02-03', 1003, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-02-01', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-01-30', 1019, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-02-01', 1017, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-01-31', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-30', '2021-02-02', 1019, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-02-02', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-01-31', 1010, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-01-31', 1006, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-02-02', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-01-31', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-01-31', 1004, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-01-31', 1003, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-02-04', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-02-03', 1016, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-01-31', '2021-02-04', 1013, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-04', 1018, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-05', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-01', 1015, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-03', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-01', 1026, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-05', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-01', 1004, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-01', '2021-02-02', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-02', '2021-02-05', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-02', '2021-02-03', 1026, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-02', '2021-02-04', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-03', '2021-02-05', 1024, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-03', '2021-02-07', 1007, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-03', '2021-02-06', 1018, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-03', '2021-02-04', 1003, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-04', '2021-02-05', 1010, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-04', '2021-02-07', 1027, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-04', '2021-02-08', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-04', '2021-02-04', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-05', '2021-02-08', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-05', '2021-02-05', 1014, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-05', '2021-02-05', 1009, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-05', '2021-02-07', 1019, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-06', '2021-02-07', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-06', '2021-02-07', 1004, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-07', '2021-02-11', 1004, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-07', '2021-02-07', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-07', '2021-02-11', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-07', '2021-02-07', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-08', 1013, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-08', 1013, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-12', 1007, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-11', 1011, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-08', 1001, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-10', 1023, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-12', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-09', 1019, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-12', 1023, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-08', '2021-02-09', 1004, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-09', '2021-02-10', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-09', '2021-02-10', 1006, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-09', '2021-02-09', 1025, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-09', '2021-02-09', 1005, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-10', '2021-02-14', 1013, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-10', '2021-02-10', 1014, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-10', '2021-02-11', 1027, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-13', 1020, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-14', 1012, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-15', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-15', 1007, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-11', 1021, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-13', 1012, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-14', 1007, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-13', 1012, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-11', '2021-02-13', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-12', 1012, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-12', 1001, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-16', 1017, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-14', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-14', 1008, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-14', 1014, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-12', '2021-02-15', 1020, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-17', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-15', 1027, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-16', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-15', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-13', 1003, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-13', 1001, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-16', 1002, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-16', 1023, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-13', '2021-02-16', 1004, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-14', '2021-02-15', 1001, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-14', '2021-02-14', 1026, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-14', '2021-02-14', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-15', '2021-02-19', 1023, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-16', 1016, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-19', 1003, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-16', 1026, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-20', 1010, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-17', 1025, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-16', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-20', 1024, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-17', 1022, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-20', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-16', '2021-02-18', 1021, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-17', '2021-02-19', 1024, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-17', '2021-02-20', 1005, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-17', '2021-02-19', 1021, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-17', '2021-02-21', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-17', '2021-02-18', 1020, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-21', 1005, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-22', 1017, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-18', 1005, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-18', 1017, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-21', 1008, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-19', 1013, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-22', 1006, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-20', 1016, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-18', '2021-02-22', 1008, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-19', '2021-02-22', 1011, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-19', '2021-02-22', 1027, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-23', 1009, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-21', 1027, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-23', 1001, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-23', 1007, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-24', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-24', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-20', '2021-02-21', 1006, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-22', 1010, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-25', 1022, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-23', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-21', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-24', 1025, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-24', 1027, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-24', 1001, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-21', '2021-02-25', 1009, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-24', 1020, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-24', 1013, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-23', 1006, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-23', 1021, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-26', 1009, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-24', 1024, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-22', '2021-02-22', 1012, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-23', '2021-02-23', 1014, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-23', '2021-02-24', 1025, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-24', 1024, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-27', 1019, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-26', 1023, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-28', 1025, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-25', 1025, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-24', 1022, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-25', 1016, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-24', 1025, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-24', '2021-02-26', 1013, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-25', '2021-02-28', 1025, 703);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-25', '2021-02-27', 1014, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-29', 1008, 708);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-26', 1018, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-27', 1004, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-29', 1009, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-29', 1002, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-26', 1025, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-26', '2021-02-27', 1005, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-28', 1007, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-03-01', 1017, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-27', 1020, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-29', 1023, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-27', 1001, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-27', 1012, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-27', 1026, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-02-28', 1021, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-27', '2021-03-01', 1020, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-29', 1025, 704);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-03-03', 1014, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-28', 1011, 705);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-28', 1021, 701);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-03-03', 1007, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-28', 1019, 702);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-29', 1002, 706);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-02-29', 1026, 707);
INSERT INTO Orders (OrderDate, OrderShipDate, CustomerID, EmployeeID)
  VALUES ('2021-02-28', '2021-03-02', 1020, 702);
